/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/templates/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить шаблон */
        get: operations["get"];
        /** Обновить шаблон */
        put: operations["update"];
        post?: never;
        /** Удалить шаблон */
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workouts/{workoutId}/exercises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Добавить упражнение в тренировку */
        post: operations["addExercise"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workouts/{workoutId}/exercises/{workoutExerciseId}/sets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Добавить подход к упражнению */
        post: operations["addSetEntry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workouts/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Запустить тренировку */
        post: operations["startWorkout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить список шаблонов */
        get: operations["list"];
        put?: never;
        /** Создать шаблон тренировки */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workouts/{workoutId}/sets/{setEntryId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Обновить подход в тренировке */
        patch: operations["updateSetEntry"];
        trace?: never;
    };
    "/api/exercises/{exerciseId}/last-max": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить последний максимум по упражнению */
        get: operations["getLastMax"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workouts/{workoutId}/exercises/{workoutExerciseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Удалить упражнение из тренировки */
        delete: operations["deleteExercise"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workouts/{workoutId}/exercises/{workoutExerciseId}/sets/{setEntryId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Удалить подход из тренировки */
        delete: operations["deleteSetEntry"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Запрос на создание или обновление шаблона тренировки */
        TemplateCreateRequest: {
            /**
             * @description Название шаблона
             * @example Грудь
             */
            name: string;
            /** @description Упражнения в шаблоне */
            exercises: components["schemas"]["TemplateExerciseRequest"][];
        };
        /** @description Упражнение в шаблоне */
        TemplateExerciseRequest: {
            /**
             * Format: int64
             * @description Идентификатор упражнения
             * @example 1
             */
            exerciseId: number;
            /**
             * Format: int32
             * @description Порядок упражнения
             * @example 1
             */
            orderIndex?: number;
            /** @description Плановые подходы */
            sets: components["schemas"]["TemplateSetRequest"][];
        };
        /** @description Плановый подход */
        TemplateSetRequest: {
            /**
             * Format: int32
             * @description Порядок подхода
             * @example 1
             */
            orderIndex?: number;
            /**
             * Format: int32
             * @description Плановые повторы
             * @example 10
             */
            plannedReps?: number | null;
            /**
             * Format: int32
             * @description Плановая длительность в секундах
             * @example 60
             */
            plannedDurationSeconds?: number | null;
            /** @description Проверка корректности набора полей */
            oneOfPlannedFieldsPresent?: boolean;
        };
        /** @description Ошибка API */
        ApiError: {
            /**
             * Format: date-time
             * @description Время ошибки
             */
            timestamp?: string;
            /** @description Путь запроса */
            path?: string;
            /**
             * @description Код ошибки
             * @example NOT_FOUND
             */
            code?: string;
            /** @description Сообщение */
            message?: string;
            /** @description Дополнительные детали */
            details?: Record<string, never> | null;
        };
        /** @description Упражнение в шаблоне */
        TemplateExerciseResponse: {
            /**
             * Format: int64
             * @description Идентификатор упражнения
             * @example 1
             */
            exerciseId?: number;
            /**
             * Format: int32
             * @description Порядок упражнения
             * @example 1
             */
            orderIndex?: number;
            /** @description Плановые подходы */
            sets?: components["schemas"]["TemplateSetResponse"][];
        };
        /** @description Ответ с шаблоном тренировки */
        TemplateResponse: {
            /**
             * Format: int64
             * @description Идентификатор шаблона
             * @example 10
             */
            id?: number;
            /**
             * @description Название шаблона
             * @example Грудь
             */
            name?: string;
            /** @description Упражнения в шаблоне */
            exercises?: components["schemas"]["TemplateExerciseResponse"][];
        };
        /** @description Плановый подход */
        TemplateSetResponse: {
            /**
             * Format: int32
             * @description Порядок подхода
             * @example 1
             */
            orderIndex?: number;
            /**
             * Format: int32
             * @description Плановые повторы
             * @example 10
             */
            plannedReps?: number | null;
            /**
             * Format: int32
             * @description Плановая длительность в секундах
             * @example 60
             */
            plannedDurationSeconds?: number | null;
        };
        /** @description Запрос на добавление упражнения в тренировку */
        AddWorkoutExerciseRequest: {
            /**
             * Format: int64
             * @description Идентификатор упражнения
             * @example 123
             */
            exerciseId: number;
            /**
             * Format: int32
             * @description Порядок упражнения
             * @example 2
             */
            orderIndex: number;
        };
        /** @description Фактический подход */
        SetEntryResponse: {
            /**
             * Format: int64
             * @description Идентификатор подхода
             * @example 5000
             */
            id?: number;
            /**
             * Format: int32
             * @description Порядок подхода
             * @example 1
             */
            orderIndex?: number;
            /**
             * Format: int32
             * @description Фактические повторы
             * @example 10
             */
            reps?: number | null;
            /**
             * @description Вес
             * @example 50
             */
            weight?: number | null;
            /**
             * Format: int32
             * @description Длительность в секундах
             * @example 60
             */
            durationSeconds?: number | null;
        };
        /** @description Упражнение в тренировке */
        WorkoutExerciseResponse: {
            /**
             * Format: int64
             * @description Идентификатор записи упражнения
             * @example 1000
             */
            id?: number;
            /**
             * Format: int64
             * @description Идентификатор упражнения
             * @example 1
             */
            exerciseId?: number;
            /**
             * Format: int32
             * @description Порядок упражнения
             * @example 1
             */
            orderIndex?: number;
            /** @description Подходы */
            sets?: components["schemas"]["SetEntryResponse"][];
        };
        /** @description Запрос на добавление подхода к упражнению */
        AddSetEntryRequest: {
            /**
             * Format: int32
             * @description Порядок подхода
             * @example 1
             */
            orderIndex: number;
            /**
             * Format: int32
             * @description Фактические повторы
             * @example 12
             */
            reps?: number | null;
            /**
             * @description Вес
             * @example 80
             */
            weight?: number | null;
            /**
             * Format: int32
             * @description Длительность в секундах
             * @example 60
             */
            durationSeconds?: number | null;
        };
        /** @description Запрос на старт тренировки */
        StartWorkoutRequest: {
            /**
             * Format: int64
             * @description Идентификатор шаблона
             * @example 10
             */
            templateId?: number | null;
            /**
             * @description Заголовок тренировки
             * @example 2026-02-01 Грудь
             */
            title?: string | null;
        };
        /** @description Ответ с тренировочной сессией */
        WorkoutSessionResponse: {
            /**
             * Format: int64
             * @description Идентификатор тренировки
             * @example 100
             */
            id?: number;
            /**
             * @description Заголовок тренировки
             * @example 2026-02-01 Грудь
             */
            title?: string;
            /**
             * Format: date-time
             * @description Дата и время старта
             */
            startedAt?: string;
            /**
             * Format: int64
             * @description Идентификатор шаблона
             * @example 10
             */
            templateId?: number | null;
            /** @description Упражнения тренировки */
            exercises?: components["schemas"]["WorkoutExerciseResponse"][];
        };
        /** @description Запрос на обновление подхода */
        UpdateSetEntryRequest: {
            /**
             * Format: int32
             * @description Порядок подхода
             * @example 1
             */
            orderIndex?: number | null;
            /**
             * Format: int32
             * @description Фактические повторы
             * @example 10
             */
            reps?: number | null;
            /**
             * @description Вес
             * @example 70
             */
            weight?: number | null;
            /**
             * Format: int32
             * @description Длительность в секундах
             * @example 45
             */
            durationSeconds?: number | null;
        };
        /** @description Ответ с последним максимумом по упражнению */
        ExerciseLastMaxResponse: {
            /**
             * Format: int64
             * @description Идентификатор упражнения
             * @example 123
             */
            exerciseId?: number;
            /**
             * Format: int64
             * @description Идентификатор последней тренировки
             * @example 456
             */
            lastWorkoutId?: number | null;
            /**
             * Format: date-time
             * @description Дата и время старта последней тренировки
             */
            lastWorkoutStartedAt?: string | null;
            /**
             * @description Максимальный вес в последней тренировке (0 если данных нет)
             * @example 80
             */
            maxWeight?: number;
            /**
             * Format: int32
             * @description Максимальная длительность в секундах в последней тренировке (0 если данных нет)
             * @example 120
             */
            maxDurationSeconds?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Шаблон */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TemplateResponse"];
                };
            };
            /** @description Шаблон не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TemplateCreateRequest"];
            };
        };
        responses: {
            /** @description Шаблон обновлен */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TemplateResponse"];
                };
            };
            /** @description Ошибка валидации */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Шаблон не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Шаблон удален */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Шаблон не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
        };
    };
    addExercise: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workoutId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddWorkoutExerciseRequest"];
            };
        };
        responses: {
            /** @description Упражнение добавлено */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WorkoutExerciseResponse"];
                };
            };
            /** @description Ошибка валидации */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Тренировка или упражнение не найдены */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
        };
    };
    addSetEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workoutId: number;
                workoutExerciseId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddSetEntryRequest"];
            };
        };
        responses: {
            /** @description Подход добавлен */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SetEntryResponse"];
                };
            };
            /** @description Ошибка валидации */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Тренировка или упражнение не найдены */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
        };
    };
    startWorkout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartWorkoutRequest"];
            };
        };
        responses: {
            /** @description Тренировка создана */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WorkoutSessionResponse"];
                };
            };
            /** @description Ошибка валидации */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Шаблон не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список шаблонов */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TemplateResponse"][];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TemplateCreateRequest"];
            };
        };
        responses: {
            /** @description Шаблон создан */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TemplateResponse"];
                };
            };
            /** @description Ошибка валидации */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
        };
    };
    updateSetEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workoutId: number;
                setEntryId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSetEntryRequest"];
            };
        };
        responses: {
            /** @description Подход обновлен */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SetEntryResponse"];
                };
            };
            /** @description Ошибка валидации */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
            /** @description Тренировка или подход не найдены */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getLastMax: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exerciseId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Последний максимум */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ExerciseLastMaxResponse"];
                };
            };
            /** @description Упражнение не найдено */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
        };
    };
    deleteExercise: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workoutId: number;
                workoutExerciseId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Упражнение удалено */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Тренировка или упражнение не найдены */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
        };
    };
    deleteSetEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workoutId: number;
                workoutExerciseId: number;
                setEntryId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Подход удален */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Тренировка или подход не найдены */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiError"];
                };
            };
        };
    };
}
